import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AnonProvider from "@components/AnonProvider";
import WalletProvider from "@components/WalletProvider";
import { type Session, getServerSession } from "next-auth";
import ToastProvider from "@components/ToastProvider";
import authOptions from "@config/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "eSIM DApp",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession(authOptions);
	return (
		<html lang="en">
			<body className={inter.className}>
				<ToastProvider>
					<WalletProvider session={session as Session}>
						<AnonProvider>{children}</AnonProvider>
					</WalletProvider>
				</ToastProvider>
			</body>
		</html>
	);
}
